### ISSUE TITLE
Texto de placeholder na página dos Hackathons

### ISSUE THREAD

**Issue by ravishi** [labhackercd/labhackercd.net#7]
> Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus...

Acho que esses trechos de Pulp Ficiton não deveriam aparecer no nosso portal.

**Comment by Fellype** [comment]
Eu falei que faltava colocar descrição e mesmo assim o @daniel870 disse pra subir ahuahauahuh

**Comment by Fellype** [comment]
done.
